### ISSUE TITLE
Add metadata parsing utility

### ISSUE THREAD

**Issue by mbsantiago** [rhine3/audiomoth-guide#15]
Hi! 
I'm starting to develop a Python tool to quickly extract AudioMoth metadata. I have a working version and I though you could be interested in adding it to your guide! It's called [metamoth](https://github.com/mbsantiago/metamoth).
For now, it only works on old firmwares (I think <1.3) but I'm planning to add support for newer ones soon.
Thanks! Santiago

**Comment by rhine3** [comment]
Hi Santiago, 

Thanks for this link! I will definitely add it to the next version of the guide.

Tessa

**Comment by rhine3** [comment]
@mbsantiago I will keep this open as a reminder to myself to add it :)

**Comment by rhine3** [comment]
Closing this and putting it into a separate updates thread (#16 ). Currently the guide is in the process of being translated into Spanish, and I am holding off on making quite a few updates until that process is complete. Then I can do a round of updates and integrate those updates into the Spanish version all at once.
