### ISSUE TITLE
Translate guide into Spanish

### ISSUE THREAD

**Issue by rhine3** [rhine3/audiomoth-guide#17]
- [x] Hand guide to translator (Marco G. S.)
  - [ ] `diff` the translated version vs. the most recent version, then retranslate the changed parts
- [ ] Go through jargon and link translations with Marco
- [ ] Incorporate updates from #16 and translate these into Spanish
- [ ] Fix hotlinks and ensure all hotlinks work in both versions
- [ ] Create parallel Spanish PDF version as well
- [ ] Use PDF-link-checker in Python to identify broken links

**Comment by YosbelM** [comment]
Hello, my name is Yosbel and I would like to translate this project from English to Spanish. I am still new to this platform and I am interested in learning and collaborating with the community. I have a good command of both languages and I am familiar with the cultural references and idioms of each one.
