### ISSUE TITLE
Quick question on the code to compute the battery life

### ISSUE THREAD

**Issue by laurenharrell** [rhine3/audiomoth-guide#18]
Hey Tessa - this guide is amazing, thank you so much for creating it! I ended up resolving my original question - but I'm curious if there's updated guidance given the recent experiment done from your lab?

**Comment by rhine3** [comment]
Hi Lauren! I do have quite a few updates we'd like to make to the guide, but currently updating it has fallen to the wayside. I've been keeping track of them in #16 so I'll add this there.

I should update the guidance (and the battery calculation code) based on the most recent experiment, as well as mention how to determine what the amperage of your batteries is (or simply mention the expected amperage of typical lithium vs. alkaline batteries).

Any particular questions I can help you answer at the moment?
