### ISSUE TITLE
Recording metadata

### ISSUE THREAD

**Issue by abfleishman** [rhine3/audiomoth-guide#3]
The new firmware writes metadata about the recording to the "Comments" field in the EXIF metadata.  This includes battery voltage, gain settings, DateTime, and most importantly Serial Number so if SD cards get mixed up you can recover what unit they were made on.
this can be accessed in many ways but an easy command line tool `exiftool` works on mac, Linux, and windows and is fast. 
here is an example: 
![image](https://user-images.githubusercontent.com/9219852/54646947-f25b6280-4a5d-11e9-9a50-2ac6336fbbfc.png)
I was going to work and make the change myself but was not sure where was the most appropriate place to put this info.

**Comment by rhine3** [comment]
This is very helpful information; thanks @abfleishman! I made a new section in the document for this information, "Recording results." I also referenced this information in the "Deployments" section, since this information could be helpful if SD cards got mixed up during a deployment.
