### ISSUE TITLE
add libraries to analysis-software?

### ISSUE THREAD

**Issue by NickleDave** [rhine3/audiomoth-guide#9]
Hi @rhine3 thank you for putting this site together.

Any chance you'd consider a PR adding the libraries I develop? They provide functionality for researchers that specifically study vocal learning, but they may be of interest to bioacoustics researchers in general. 

For classification there's [`hybrid-vocal-classifier`](https://github.com/NickleDave/hybrid-vocal-classifier) (basically a wrapper around scikit-learn) and [`vak`](https://github.com/NickleDave/vak)(wrapper around PyTorch). `vak` I developed with @yardencsGitHub to benchmark a neural network model he designed, [TweetyNet](https://github.com/yardencsGitHub/tweetynet). 

And for working with annotation there's [crowsetta](https://github.com/NickleDave/crowsetta).

I have been working very hard to develop these tools and would really appreciate if you could help me reach the community you are trying to build around audiomoth.

Thank you!

**Comment by rhine3** [comment]
Hi there @NickleDave,

Yes, I would love to pull in any additions of libraries that you've developed or come across!

Tessa

**Comment by NickleDave** [comment]
🙌 thank you @rhine3 I had it on my to-do list to submit a PR but kept failing to get to it. 
Much obliged
